CREATE TABLE sala (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    capacidade NUMBER NOT NULL
);

COMMENT ON TABLE sala IS 'Tabela de salas de aula';
COMMENT ON COLUMN sala.id IS 'Identificador da sala';
COMMENT ON COLUMN sala.nome IS 'Nome da sala';
COMMENT ON COLUMN sala.capacidade IS 'Capacidade de alunos da sala';
