CREATE TABLE aula (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    data DATE NOT NULL,
    sala_id NUMBER NOT NULL,
    CONSTRAINT fk_sala FOREIGN KEY (sala_id) REFERENCES sala(id)
);

COMMENT ON TABLE aula IS 'Tabela de aulas';
COMMENT ON COLUMN aula.id IS 'Identificador da aula';
COMMENT ON COLUMN aula.nome IS 'Nome da aula';
COMMENT ON COLUMN aula.data IS 'Data da aula';
COMMENT ON COLUMN aula.sala_id IS 'Identificador da sala de aula';

