CREATE TABLE pessoa (
    CREATE TABLE pessoa (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        data_nascimento DATE NOT NULL
    );

    COMMENT ON TABLE pessoa IS 'Tabela de pessoas';
    COMMENT ON COLUMN pessoa.id IS 'Identificador da pessoa';
    COMMENT ON COLUMN pessoa.nome IS 'Nome da pessoa';
    COMMENT ON COLUMN pessoa.data_nascimento IS 'Data de nascimento da pessoa';